## versions ############################################################################################################
[versions]
## SDK
minSdk = "23"
targetSdk = "31"
compileSdk = "31"
## Debug
debugVersionCode = "1"
debugVersionName = "1.0.0"
## App?
gradle = "7.1.3"
kotlin = "1.6.21"
## Kotlin
core = "1.8.0"
coroutines = "1.6.2"
## Checks
detekt = "1.20.0"
ktlint = "10.3.0"
# checkstyle = "10.3"
gradlevers = "0.42.0"
## Android
appcompat = "1.4.2"
material = "1.6.1"
constraintlayout = "2.1.4"
recyclerview = "1.2.1"
swiperefreshlayout = "1.1.0"
activity = "1.4.0"
fragment = "1.4.1"
lifecycle = "2.4.1"
preferences = "1.2.0"
## Network
retrofit = "2.9.0"
okHttp = "4.9.3"
picasso = "2.71828"
glide = "4.13.2"
## DI
hilt = "2.42"
## Log
timber = "5.0.1"
## Test
junit4 = "4.13.2"
extJunit = "1.1.3"
mockito = "3.12.4"
## Misc
splashscreen = "1.0.0-beta02"

## libraries ###########################################################################################################
[libraries]
## Kotlin
core = { module = "androidx.core:core-ktx", version.ref = "core" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
## Android
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
## Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
## DI
## hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
## hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }
## Log
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
## Test
junit4 = { module = "junit:junit", version.ref = "junit4" }
extJunit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
# checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
## Misc
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

## bundles #############################################################################################################
[bundles]
## Android
android = ["appcompat", "material", "constraintlayout"]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]
## Network
retrofit-moshi = ["retrofit", "retrofit-converter-moshi"]
retrofit-gson = ["retrofit", "retrofit-converter-gson"]

## plugins #############################################################################################################
[plugins]
## Android
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
## Kotlin
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
## Checks
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
gradlevers = { id = "com.github.ben-manes.versions", version.ref = "gradlevers" }
## DI
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }